// <auto-generated />
using Ispit.Data.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Ispit.Data.Migrations
{
    [DbContext(typeof(TodoListContext))]
    [Migration("20231221093021_PodaciUBazi")]
    partial class PodaciUBazi
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Ispit.Data.Models.TodoList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("TodoLists");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Nađi večeru",
                            IsCompleted = false,
                            Title = "Trgovina"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Kako pobjeći bez traga",
                            IsCompleted = false,
                            Title = "Bijeg"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Što raditi poslije spavanja",
                            IsCompleted = false,
                            Title = "U suton"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Zaboraviti noćne more",
                            IsCompleted = false,
                            Title = "Snovi"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
